---
- hosts: 172.31.25.113 
  become: yes
  tasks:
  - include_tasks: myfile.yml 

  - name: i want install apache2 webserver
    apt:
       name: apache2
       state: present

  - name: i want restart apache2 webserver
    apt:
      name: apache2
      state: restarted     