---
- hosts: 172.31.25.113 
  become: yes
  tasks:
  - include_tasks: myfile.yml 

  - name: i want to install apache2 webserver
    apt:
       name: apache2
       state: present

  - name: i want to restart apache2 webserver
    service:
      name: apache2
      state: restarted   
      
  - name: copy index.j2 file into ansible node side    
    template:
      src: index.j2
      dest: /var/www/html/index.html  