---
- hosts: 172.31.25.113  
  become: yes
  tasks:
  - name: i want install git, tree, wget
    apt:
      name: "{{ item }}"
      state: present 
    loop:
      - git
      - tree
      - wget        