---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu
    apt:
      name: "{{mywebonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: i want to start webserver on ubuntu
    service:
      name: "{{mywebonubuntu}}"
      state: started
    when: ansible_os_family =="Debian"
    
    


  - name: i want to install webserver on RedHat
    yum:
      name: "{{mywebonRedHat}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: i want to start webserver on RedHat
    service:
      name: "{{mywebonubuntu}}"
      state: started
    when: ansible_os_family =="RedHat"     